# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TABLEFLIP Blog
email: hello@tableflip.io
description: the TABLEFLIP blog musings for everyone
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.tableflip.io" # the base hostname & protocol for your site
twitter_username: _tableflip
github_username:  tableflip

# Build settings
markdown: kramdown

kramdown:
  hard_wrap: true
  input: GFM

highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "posts"
      published: true
  -
    scope:
      path: ''
      type: author
    values:
      permalink: "author/:slug/"
      layout: author

sass:
    sass_dir: _sass

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

collections:
  author:
    output: true
    permalink: /author/:slug

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "package.json"]
include: [".well-known", ".datignore"]
